# Generated by Django 5.1 on 2024-10-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0006_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_name',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
