# Generated by Django 5.1 on 2024-10-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0008_alter_post_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_name',
            field=models.ImageField(blank=True, default='blog_images/default_blog.png', null=True, upload_to='blog_images'),
        ),
    ]
