# Generated by Django 5.1 on 2024-10-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0009_alter_post_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pictures/default_profile.webp', null=True, upload_to='profile_pictures'),
        ),
    ]
